services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    pythonVersion: 3.9  # Or whichever version you want to use (e.g., 3.10)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

